Repository rh-ecosystem-edge/NVIDIA-gpu-add-on-init-container, pull requests merged in 2022-03, with the labels that each got.

#16 Update OWNER_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, ok-to-test

#18 Cleanup OWNER_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#17 Optimize final image size and rebase on full UBI
  Dockerfile.gpu_init
  Makefile
Labels: enhancement, lgtm, approved
